spring.application.name=gitdemo

spring.datasource.url=jdbc:postgresql://ep-raspy-sound-aojendwl-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_fIblh1wDFrE9

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=2