spring.application.name=gitdemo

spring.datasource.url=jdbc:postgresql://ep-raspy-sound-aojendwl-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fIblh1wDFrE9&sslmode=require&channelBinding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect